### ISSUE TITLE
Can't build with Nim v1.2.18

### ISSUE THREAD

**Issue by michaelsbradleyjr** [nim-lang/langserver#12]
When running `nimble build` in a clone of this repo with Nim v1.2.18 installed via `choosenim`, there is an error:
```
/path/to/repos/langserver/suggestapi.nim(198, 103) template/generic instantiation of `async` from here
/path/to/repos/langserver/suggestapi.nim(226, 32) template/generic instantiation of `await` from here
/path/to/.choosenim/toolchains/nim-1.2.18/lib/pure/asyncmacro.nim(455, 10) Error: Await only available within .async
```

**Comment by yyoncho** [comment]
As per my discussion with @zah  most likely we won't support 1.2 (cc-ing him to share if this is still the case). In general, since nimlangserver is only a shim we don't need it to explicitly build with 1.2 as long as it can work with `nimsuggest` version 1.2 . Meanwhile, I will take a look if it will be easy to make it build with 1.2.

**Comment by yyoncho** [comment]
I have pushed 5e42b65b3c12bf67e679e71ce0b2206aa7be6f23 which fixes the build issues but it still needs https://github.com/nim-lang/Nim/pull/19719 to pass the tests and function properly

**Comment by yyoncho** [comment]
As a side note, building the server with 1.6 should be fine because the server is just a wrapper over `nimsugest`.

**Comment by yyoncho** [comment]
Heads up: I started working on reworking nimsuggest and it is very likely that we are not going to support 1.2. Here it is the initial PR.

**Comment by michaelsbradleyjr** [comment]
Thanks for the heads up, very much looking forward to a bright future for nim-lang/langserver. Thanks for your hard work on this project!
