### ISSUE TITLE
Some functions do not work properly in Neovim.

### ISSUE THREAD

**Issue by VanshBhatia2192** [nim-lang/langserver#229]
I have setup nim-langserver on neovim using nvim-lspconfig plugin and I'm getting partial results from the autocomplete. 
for example, I can see function definitions but it does not suggest any keywords or imports. 

I have tried this on two operating systems with configuration as follows:
1. Darwin Vanshs-MacBook-Air-3.local 23.6.0 Darwin Kernel Version 23.6.0 - (M1 chip)
2. Linux cypher 6.6.47-gentoo-cust #6 SMP PREEMPT_DYNAMIC  x86_64 AMD Ryzen 7 5800U with Radeon Graphics AuthenticAMD GNU/Linux

LSP config for nim is: 
![WhatsApp Image 2024-09-10 at 12 58 38 PM](https://github.com/user-attachments/assets/b4599b53-8573-48eb-9ee8-5694d4a495a2)
LSP log :
[lsp.log](https://github.com/user-attachments/files/16941097/lsp.log)
Example screenshots where we expect suggestions:
![WhatsApp Image 2024-09-10 at 12 57 12 PM](https://github.com/user-attachments/assets/fc674c6c-b92c-4651-909b-addd5029d2c8)
![WhatsApp Image 2024-09-10 at 12 57 31 PM](https://github.com/user-attachments/assets/2d277132-4652-4c99-b096-2980946c2633)
![WhatsApp Image 2024-09-10 at 12 57 39 PM](https://github.com/user-attachments/assets/e73bf1d1-2eab-40e1-83e8-b4284d072ca5)

for reference all of this works perfectly on VS code using any available nim extension.

any help would be appreciated.
(ps: i have been trying to make this work for the last 5 hours, I am on the verge of crying)

**Comment by VanshBhatia2192** [comment]
VS code also uses nimsuggest for suggestions. check the screen shots for refernece.

<img width="812" alt="Screenshot 2024-09-10 at 6 54 38 PM" src="https://github.com/user-attachments/assets/02b1fca2-b24b-40ac-8f9f-a028d263a845">
<img width="862" alt="Screenshot 2024-09-10 at 6 54 48 PM" src="https://github.com/user-attachments/assets/2308461f-07f4-4d45-9cee-c07
<img width="1351" alt="Screenshot 2024-09-10 at 6 55 55 PM" src="https://github.com/user-attachments/assets/45f04bc8-c37c-44ef-8156-8f63d0d729a9">
7699e1a44">

**Comment by jmgomez** [comment]
I see what you mean now, no idea why that happens though, it seems like they are being filtered somehow by the client. Will take a look when I have the chance, but feel free to debug it further and submit a PR

**Comment by jmgomez** [comment]
There is a verbosity setting: `notificationVerbosity` 
In the VSCode is not an issue because it has its custom panel for notifications. You can extend the Neovim plugin to do something similar if you wish to do so, you need to subscribe to the `window/showMessage` notification

**Comment by jmgomez** [comment]
What version of the lsp are you using?

**Comment by Pranay224** [comment]
Alright so I checked what nimble install nimlangserver installed and it was version 1.4.0 I believe. I downloaded the latest version being 1.5.2 and built it from source which then fixed the constant respawning of nimsuggest processes. Thanks for the pointer!

**Comment by Pranay224** [comment]
Could you give me a few points as to where I should start to investigate? I'd be glad to help fix this issue if I can pinpoint the problem.

**Comment by Pranay224** [comment]
I might have also come across another issue regarding the lsp server not providing the intended functionality, that being the lack of indentations. The editor automatically adds proper indentation to some statements (specifically to those which are identical to python it seems such as an if, while and for) and nothing when it is nim specific (proc, when, var, let, const etc).
Is this a lsp issue or is it handled by something else entirely?

**Comment by jmgomez** [comment]
> Could you give me a few points as to where I should start to investigate?

You can start here: 
https://github.com/nim-lang/langserver/blob/737eea06b97abbdfb7361626ef189c06fcb5ed6e/routes.nim#L114

if you add a `debug` call (see how it's used in other places) you can inspect what's being return by the server from suggestions at this point. 

> Is this a lsp issue or is it handled by something else entirely?

AFAIK lsp is not handling it. We are about to add format support but it isnt in there yet.

**Comment by Pranay224** [comment]
Alright so I spent some time digging into how this was working and I now believe that the problem might be in nimsuggest itself and not the lsp. Instead of adding a debug call to the lsp, I manually hooked up a nimsuggest instance to my file and replayed the commands the lsp sent to the nimsuggest process to see how it would react and got results that do somewhat explain the lackluster results of the lsp. Nimsuggest simply doesn't work half the time when it's asked to provide data. I've got a few examples here:

1. I opened a new file and just wrote 'discard 0' into it. I unsurprisingly didn't get any suggestion while writing discard. So I deleted a part of the line, leaving only 'disc' left and tried to ask nimsuggest to suggest what would come next. 
![image](https://github.com/user-attachments/assets/24102987-6e78-4794-a169-72714e4a50eb)
And nimsuggest itself failed to respond, leaving the lsp helpless as well
Here's the lsp log for this interaction: 
[lsp.log](https://github.com/user-attachments/files/17022224/lsp.log)

2. I then opened up a demo program I wrote:
```
type
  ListNode*[T] = ref object
    data: T
    next: ListNode[T]

  LinkedList*[T] = object
    head: ListNode[T]


proc newLinkedList*[T](): LinkedList[T] =
  result = LinkedList[T](head: nil)

proc pushFront*[T](list: var LinkedList[T], data: T) =
  let newNode = ListNode[T](data: data, next: list.head)
  list.head = newNode

proc popFront*[T](list: var LinkedList[T]): T =
  if list.head == nil:
    raise newException(ValueError, "List is empty")

  result = list.head.data
  list.head = list.head.next
```

I then put my cursor on the 'list.head' field in the pushFront proc and asked for the type signature, and got back nothing. I tried it again manually in nimsuggest and yet again, 
![image](https://github.com/user-attachments/assets/49d3bef6-6675-40e6-9cc8-e66579362f2b)
Nothing.
(One thing of note is, if I add a main proc, create and use a linkedlist inside the main proc and then call the main proc, the signature help starts working. I've no idea why this happens this way or what triggers the signatures to start working. I tried to see if it would suggest keywords now but it still doesn't do that)
lsp log, once again: 
[lsp.log](https://github.com/user-attachments/files/17022257/lsp.log)

So it seems that nimsuggest itself isn't working properly half the time, so I can't even expect the lsp to work since all it does is query nimsuggest and display the results.

**Comment by Araq** [comment]
Well there is nothing surprising about it, nimsuggest cannot provide type hints in generic code since Nim itself doesn't typecheck generic code. Ta-da! Once you instantiated your generic, things have a somewhat better chance of working.

Also, nimsuggest doesn't suggest "keywords", it's not its job. Could be implemented but it's rather silly. Oh no, you have to type out short words. Nimsuggest is for navigation and API exploration.

**Comment by Pranay224** [comment]
Alright that clears up things a lot, thanks for pitching in. I do wonder if the lsp also being unable to suggest fields of objects as I'm working on writing code due to it being generic as well?

**Comment by Araq** [comment]
Yup. Type-checking generic code is coming in Nim 3 btw.

**Comment by Pranay224** [comment]
So all of my problems are either not even problems to begin with or features that aren't implemented yet. So all in all, everything is working just as intended, except for a few more IDE features like goto definition since that falls under navigation that I think really should be working but I guess I'll take a look to see if something is amiss. Thanks for all the support so far.
