### ISSUE TITLE
could not load: pcre64.dll 

### ISSUE THREAD

**Issue by lost22git** [nim-lang/langserver#85]
## version

|k|v|
|:---:|:---:|
|os|win11|
|nim|2.0.2|
|nimble|v0.14.2|

## installation method
`nimble install nimlangserver`

## error
```bash
❯ nimlangserver
could not load: pcre64.dll
```

**Comment by davidvfx07** [comment]
For anybody else facing this issue, the problem is likely as simple as a missing dll. I fixed this for myself by reinitializing my installation with choosenim. To verify everything is where it should be, open your terminal and run `> choosenim stable`, and if you haven't in a while, it's also a good idea to run `> choosenim update stable` to download and install the latest nim version.

**Comment by arnetheduck** [comment]
cc @jmgomez should be trivial to move to nim-regex, `std/re` is a dead end.

**Comment by Araq** [comment]
True but also, why does it need regexes to begin with.

**Comment by arnetheduck** [comment]
some filename filtering from the looks of it

**Comment by jmgomez** [comment]
https://github.com/nim-lang/langserver/pull/259
